language: node_js
node_js:
- 10
branches:
  only:
  - master
before_script:
- npm install
script:
- if [ "$TRAVIS_BRANCH" = "master" ]; then ng build --prod; fi
deploy:
  provider: heroku
  api_key:
    secure: PTaS2h+D2VpFNSs+8EIKfGyhiI0dR2ZWg9/CJ01H6RhRSdVaJdhlbcCJzVOgxFMZZnR8pHhXL6nFbIM3uATsq5dscq9Sv2EiU/rj0HDHUppm8qJBUvAYPvUF/IaOPtyNSpwokrEzJFs8susXWO1y57RDgLExgrYBUY6lUEmNVYE2yv7t8j/45OpeqnIwEJYxb3rYy1veA3IhnrO3CnX6az3Za3+jh2mSD9HqueCFErbycEdwarXrRjFxjJM1srt5MnnxTjL0dGEnSFqfKI73KttootqfeU7k23ywfc2bqg7DwKqTC1yLBvK7j8EUDVrkLSTsKpLzQMIBZ95VO6g/NECPkjTv/L/FsQIIFKv8W0FtEWFlsDox/17WkeX1Ynmgpe+2ggqqjAsLmYMYI/ZKR5UzVmtJGHz565bvPCAfqX4w0m2Jxwp8CZb75tYPrY0hs4zDLSiHKMnpO8vcLC/SavzNQncAly3Zx3z9gksNQKMmLCytR8ez2RurOn4qiHvhMdrdNPTXUIdsP0ftGfezyJfalkaMOR0H48kPW1Bn9vx8eNiwxYbvYWipXZaJdyFKbFqqcedtteRaNbyLi21WfCo7fzer40SVV8vmrCZMnsAAsqeyaH3ceg2mNNS9GbfoBjRjqEcAiLdoMst8BDjYw3m3bACbTsH4uCubUsGLSAw=
