language: node_js
node_js:
  - 10
branches:
  only:
  - master
before_script:
  - npm install
script:
  - if [ "$TRAVIS_BRANCH" = "master" ]; then ng build --prod; fi
after_success:
  - if [ "$TRAVIS_BRANCH" = "master" ]; then firebase use production; fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then firebase deploy --token $FIREBASE_TOKEN --non-interactive; fi
